### ISSUE TITLE
Formatting issues when searching

### ISSUE THREAD

**Issue by christopher-wong** [ryanhugh/searchneu#46] opened 2017-12-13 21:54 UTC
When typing in the search box on first page load, the search bar gets overlaid on top of the first search result ([Screenshot](https://www.dropbox.com/s/6jha38i5gygpdf4/Screen%20Shot%202017-12-13%20at%204.52.29%20PM.png?dl=0)). Refreshing the page (or collapsing it to change the breakpoint fixes the formatting).

macOS High Sierra 10.13.2 using Safari 11.0.2

**Comment by edward-shen** [comment] 2017-12-13 22:00
I have a feeling this is related to #27, and should go away once there's a rewrite (#40) of the rendering.

@ryanhugh Can you verify this? I can't seem to reproduce it in Chrome, and I don't have a mac to test it. Maybe we can make a quick fix.

**Comment by ryanhugh** [comment] 2017-12-13 22:28
@christopher-wong Do you need to change the size of the browser window to make this happen?

I also don't have a mac to verify with me right now but will next week and can check then. This might be different than #27 because it looks like here the search box and the header are not moving at all, but in #27 the results are just not positioned correctly.  

I'll look into it next week when I have access to a mac!

**Comment by christopher-wong** [comment] 2017-12-13 22:35
@ryanhugh nope this happens on the first page load, without changing the window size. changing the window size actually fixes the problem.

**Comment by ryanhugh** [comment] 2017-12-13 22:42
Weird! I'l take a look at it next week.

**Comment by edward-shen** [comment] 2017-12-13 22:54
Just for further diagnosis, did you load directly into the site, (searchneu.com/cs3500) or did you go to the root domain, then search cs3500?

**Comment by christopher-wong** [comment] 2017-12-13 22:56
Loading directly into searchneu.com/cs3500 works perfectly. Going to the root domain and typing into the search box causes the issue described above.

**Comment by ryanhugh** [comment] 2017-12-31 02:44
Looks like this was due to a bug in safari not supporting transformY and calc in css together. 
Should be fixed in https://github.com/ryanhugh/searchneu/commit/9ea7ada365dd85f96dd9d1d6a3f0dbae86395bf6!

Just pushed the fix to prod - let me know if you still see it!

**Closed by ryanhugh** 2017-12-31 02:44 UTC
Labels: bug
