### ISSUE TITLE
Filter by "Online" vs "On-Ground" classes

### ISSUE THREAD

**Issue by joshpeyok** [ryanhugh/searchneu#6] opened 2017-11-07 19:06 UTC

**Comment by ryanhugh** [comment] 2017-11-07 19:49
When we add a filter, this will definitely be one of the options! Marking a duplicate of #1

**Closed** 2017-11-07 19:50 UTC

**Comment by ryanhugh** [comment] 2017-11-13 05:21
Btw, here's a list of all the online classes in the Spring of 2018
