### ISSUE TITLE
Searching for "CS 4710" results in "ENGL 4710" as first result

### ISSUE THREAD

**Issue by edward-shen** [ryanhugh/searchneu#59] opened 2018-04-12 02:31 UTC
Expected behavior: The card for CS 4710 appears as the first result
Actual behavior: The card for ENGL 4710 appears as the first result, then CS4710
Attempted search fields: "CS4710", "CS 4710".
![2018-04-11-222849_928x976_scrot](https://user-images.githubusercontent.com/6173958/38653289-0663dd90-3dd8-11e8-8d3a-c47d43f6ddb1.png)

**Comment by ryanhugh** [comment] 2018-04-28 09:59
Yeah... We have found a couple other instances of this same problem. It is because the current search library we are using (elasticlunr.js) trims off the S's from words that end with an S. This means that plural words will match singular words which is good for searching through paragraphs, etc, but not for searching through stuff like this. This will be fixed when we move to Amazon's Cloudsearch.

**Comment by ryanhugh** [comment] 2018-04-28 10:02
Closing as a duplicate of #21

**Closed by ryanhugh** 2018-04-28 10:02 UTC
